In [2]:
import pandas as pd 
forest_data = pd.read_csv("forestfires.csv") 
forest_data

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

In [7]:
by_data = forest_data.groupby(["month", "day"])
by_data_mean = by_data["rain", "wind"].mean()
print(by_data_mean.head(20))

               rain      wind
month day
apr   fri  0.000000  3.100000
      mon  0.000000  3.100000
      sat  0.000000  4.500000
      sun  0.000000  5.666667
      thu  0.000000  5.800000
      wed  0.000000  2.700000
aug   fri  0.066667  4.766667
      mon  0.000000  2.873333
      sat  0.000000  4.310345
      sun  0.025000  4.417500
      thu  0.000000  3.503846
      tue  0.300000  4.567857
      wed  0.000000  3.520000
dec   fri  0.000000  4.900000
      mon  0.000000  8.500000
      sun  0.000000  8.500000
      thu  0.000000  4.900000
      tue  0.000000  8.500000
      wed  0.000000  8.000000
feb   fri  0.000000  4.820000

/var/folders/9m/ztkm5bns0x1b521x6wdpd4640000gn/T/ipykernel_15333/284390352.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  by_data_mean = by_data["rain", "wind"].mean()

In [12]:
df_1 = pd.read_csv("restaurant-1.csv")
df_2 = pd.read_csv("restaurant-2.csv")
df_3 = pd.merge(df_1,df_2,how = "inner",on= "unique_id")
df_3.head()

,name,address,city,cuisine,unique_id,name_2,address_2,city_2,cuisine_2
0,arnie morton's of chicago,"""435 s. la cienega blvd.""","""los angeles""","""steakhouses""",'0',arnie morton's of chicago,"""435 s. la cienega blv.""","""los angeles""","""american"""
1,art's deli,"""12224 ventura blvd.""","""studio city""","""delis""",'1',art's delicatessen,"""12224 ventura blvd.""","""studio city""","""american"""
2,bel-air hotel,"""701 stone canyon rd.""","""bel air""","""californian""",'2',hotel bel-air,"""701 stone canyon rd.""","""bel air""","""californian"""
3,cafe bizou,"""14016 ventura blvd.""","""sherman oaks""","""french bistro""",'3',cafe bizou,"""14016 ventura blvd.""","""sherman oaks""","""french"""
4,campanile,"""624 s. la brea ave.""","""los angeles""","""californian""",'4',campanile,"""624 s. la brea ave.""","""los angeles""","""american"""

In [15]:
df_3_result = df_3[["name","cuisine_2"]]
df_3_result.head(20)

                           name       cuisine_2
0     arnie morton's of chicago      "american"
1                    art's deli      "american"
2                 bel-air hotel   "californian"
3                    cafe bizou        "french"
4                     campanile      "american"
5               chinois on main        "french"
6                        citrus   "californian"
7           fenix at the argyle      "american"
8                       granita   "californian"
9                    grill  the      "american"
10                        katsu         "asian"
11                  l'orangerie        "french"
12  le chardonnay (los angeles)        "french"
13               locanda veneta       "italian"
14                    matsuhisa         "asian"
15      palm  the (los angeles)      "american"
16                       patina   "californian"
17        philippe the original      "american"
18                 pinot bistro        "french"
19            rex il ristorante       "italian"