In [1]:
import pandas as pd 
m_news = pd.read_csv("megamart_newsales.csv")
m_news.head()

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
0,AZ-2011-1902971,"Wilson Jones Binding Machine, Clear",0.0,339,102,7,Office Supplies,Binders
1,AZ-2011-1916360,"Dania 3-Shelf Cabinet, Mobile",0.0,288,20,2,Furniture,Bookcases
2,AZ-2011-1916555,"Eldon Folders, Single Width",0.4,61,7,6,Office Supplies,Storage
3,AZ-2011-1930058,"Sanford Markers, Easy-Erase",0.0,71,1,3,Office Supplies,Art
4,AZ-2011-1967754,"Logitech Numeric Keypad, USB",0.0,93,40,2,Technology,Accessories

In [5]:
m_news.shape

(9, 8)

In [2]:
m_sales = pd.read_csv("megamart_sales.csv")
m_sales.head()

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category
0,AZ-2011-1029887,"Novimex Color Coded Labels, 5000 Label Set",0.0,26,7,2,Office Supplies,Labels
1,AZ-2011-107716,"Deflect-O Door Stop, Erganomic",0.0,85,15,2,Furniture,Furnishings
2,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories
3,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines
4,AZ-2011-1362199,"Sanford Pens, Fluorescent",0.5,25,-11,4,Office Supplies,Art

In [4]:
m_sales.shape

(59, 8)

In [6]:
combine_frame = [m_sales,m_news]
total_sales = pd.concat(combine_frame,axis = 0,ignore_index=True)
total_sales.groupby(by="Category").Sales.sum()

Category
Furniture          2460
Office Supplies    7970
Technology         8588
Name: Sales, dtype: int64

In [7]:
total_sales = pd.concat(combine_frame,axis = 0,ignore_index = True)
total_sales.groupby(by= "Category").Sales.sum()

Category
Furniture          2460
Office Supplies    7970
Technology         8588
Name: Sales, dtype: int64

In [10]:
total_sales.drop_duplicates(subset=None,keep='first',inplace = True)
total_sales.groupby(by='Category').Sales.sum()

Category
Furniture          2460
Office Supplies    6964
Technology         7494
Name: Sales, dtype: int64

In [12]:
total_sales.groupby(by=['Category','Sub-Category']).Profit.sum()

Category         Sub-Category
Furniture        Bookcases        308
                 Chairs           -49
                 Furnishings       74
Office Supplies  Appliances       229
                 Art              275
                 Binders          156
                 Envelopes         35
                 Fasteners         10
                 Labels            30
                 Paper             15
                 Storage          192
                 Supplies         103
Technology       Accessories      215
                 Copiers            0
                 Machines         168
                 Phones          1618
Name: Profit, dtype: int64

In [14]:
total_sales['Order no']=total_sales['Order ID'].str.split('-')
total_sales['Order no']=total_sales['Order no'].apply(lambda x: x[2])
total_sales['no_of_digits']=total_sales['Order no'].apply(lambda x: len(x))
total_sales['no_of_digits'].value_counts()

7    54
6     7
Name: no_of_digits, dtype: int64

In [15]:
top_25=total_sales.sort_values(by='Sales', ascending=False)
top_25=top_25.iloc[:25,]
top_25['Category'].value_counts()

Office Supplies    11
Technology          9
Furniture           5
Name: Category, dtype: int64

In [16]:
highest_order=total_sales.loc[(total_sales['Sales']>250) & (total_sales['Profit']>50)]
highest_order=highest_order.sort_values(by='Sales',ascending=False) 
print(highest_order)

           Order ID                         Product Name  Discount  Sales  \
30  AZ-2011-1410648         Nokia Smart Phone, Full Size       0.0   1908
58   AZ-2011-176674                Hoover Microwave, Red       0.1   1667
8   AZ-2011-1174243     Nokia Audio Dock, with Caller ID       0.0   1334
20  AZ-2011-1322840     Motorola Headset, with Caller ID       0.0    957
3   AZ-2011-1372644           Panasonic Printer, Durable       0.0    800
18  AZ-2011-1406494         Fellowes Lockers, Industrial       0.1    748
39  AZ-2011-1536006      Logitech Keyboard, Programmable       0.0    666
33  AZ-2011-1445262          Apple Smart Phone, Cordless       0.0    636
31   AZ-2011-144325        Bush Stackable Bookrack, Pine       0.0    630
14  AZ-2011-1260928        Eldon File Cart, Single Width       0.1    576
12  AZ-2011-1253407       Safco Stackable Bookrack, Pine       0.1    541
48  AZ-2011-1672552      Binney & Smith Sketch Pad, Blue       0.0    510
52  AZ-2011-1722024               Cisco Audio Dock, VoIP       0.0    364
59  AZ-2011-1902971  Wilson Jones Binding Machine, Clear       0.0    339
17   AZ-2011-130330     Office Star Chairmat, Adjustable       0.1    307
2   AZ-2011-1087704        Belkin Flash Drive, Bluetooth       0.0    294

    Profit  Quantity         Category Sub-Category Order no  no_of_digits
30     820         3       Technology       Phones  1410648             7
58     185         6  Office Supplies   Appliances   176674             6
8      200         8       Technology       Phones  1174243             7
20     316        12       Technology       Phones  1322840             7
3      168         3       Technology     Machines  1372644             7
18     283         4  Office Supplies      Storage  1406494             7
39      66         9       Technology  Accessories  1536006             7
33     140         1       Technology       Phones  1445262             7
31     132         5        Furniture    Bookcases   144325             6
14      51         5  Office Supplies      Storage  1260928             7
12     156         4        Furniture    Bookcases  1253407             7
48     132        11  Office Supplies          Art  1672552             7
52     142         2       Technology       Phones  1722024             7
59     102         7  Office Supplies      Binders  1902971             7
17      99         5        Furniture       Chairs   130330             6
2      109         7       Technology  Accessories  1087704             7

In [ ]:
upgrad shows df3=df.loc[(df['Sales']>250) & (df['Profit']>50)]
df3=df3.sort_values(by='Sales',ascending=False)

In [17]:
lowest_profit=total_sales[total_sales.Profit>0]
lowest_profit=lowest_profit.loc[lowest_profit.Category=='Technology']
lowest_profit['Profit_per_qty']=lowest_profit['Profit']/lowest_profit['Quantity']
lowest_profit.sort_values(by='Profit_per_qty',ascending=True)

,Order ID,Product Name,Discount,Sales,Profit,Quantity,Category,Sub-Category,Order no,no_of_digits,Profit_per_qty
39,AZ-2011-1536006,"Logitech Keyboard, Programmable",0.0,666,66,9,Technology,Accessories,1536006,7,7.333333
2,AZ-2011-1087704,"Belkin Flash Drive, Bluetooth",0.0,294,109,7,Technology,Accessories,1087704,7,15.571429
63,AZ-2011-1967754,"Logitech Numeric Keypad, USB",0.0,93,40,2,Technology,Accessories,1967754,7,20.000000
8,AZ-2011-1174243,"Nokia Audio Dock, with Caller ID",0.0,1334,200,8,Technology,Phones,1174243,7,25.000000
20,AZ-2011-1322840,"Motorola Headset, with Caller ID",0.0,957,316,12,Technology,Phones,1322840,7,26.333333
3,AZ-2011-1372644,"Panasonic Printer, Durable",0.0,800,168,3,Technology,Machines,1372644,7,56.000000
52,AZ-2011-1722024,"Cisco Audio Dock, VoIP",0.0,364,142,2,Technology,Phones,1722024,7,71.000000
33,AZ-2011-1445262,"Apple Smart Phone, Cordless",0.0,636,140,1,Technology,Phones,1445262,7,140.000000
30,AZ-2011-1410648,"Nokia Smart Phone, Full Size",0.0,1908,820,3,Technology,Phones,1410648,7,273.333333